project:
  type: website

website:
  title: "Loop"
  navbar:
    logo: ./resources/alphaLoopLogo.png
    left:
      - href: index.qmd
        text: Home
      - href: team.qmd
        text: Team
      - href: references.qmd
        text: References
      - href: talks.qmd
        text: Talks
      - href: https://wiki.alphaloop.ch
        text: Wiki
      - href: https://github.com/alphal00p/alphaloop
        text: GitHub
format:
  html:
    theme:
      dark: darkly
      light: flatly
    fontsize: 13pt
    css: styles.css
    toc: true



